use std::io::IsTerminal;

use anyhow::Result;
use serde::Serialize;

use crate::{parse_unit, systemctl, unit, SortOrder};

#[derive(Serialize)]
struct Entry {
    name: String,
    #[serde(rename = "type")]
    type_str: &'static str,
    schedule: String,
    command: String,
    status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
    /// True when the unit was generated by an older sdtab template and can be upgraded
    /// in-place via `sdtab upgrade`. Legacy units still work but miss newer directives.
    #[serde(skip_serializing_if = "std::ops::Not::not")]
    legacy: bool,
    #[serde(skip)]
    sort_key: u64, // datetime sort key for timers, u64::MAX for services
    #[serde(skip)]
    section: Section,
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Section {
    Timer,    // active timers (sorted by next run)
    Service,  // always-running services
    Disabled, // stopped timers/services
}

pub fn run(json: bool, sort: SortOrder) -> Result<()> {
    let units = parse_unit::scan_all_units()?;

    if units.is_empty() {
        if json {
            println!("[]");
        } else {
            println!("No timers or services found.");
        }
        return Ok(());
    }

    let mut entries: Vec<Entry> = Vec::new();

    for unit in &units {
        let (type_str, schedule, status, sort_key, section) = match unit.unit_type {
            parse_unit::UnitType::Service => {
                let service_unit = unit::service_filename(&unit.name);
                let active_state = systemctl::show_property(&service_unit, "ActiveState")
                    .unwrap_or_else(|_| "unknown".to_string());
                let section = if active_state == "active" {
                    Section::Service
                } else {
                    Section::Disabled
                };
                ("service", "@service".to_string(), active_state, u64::MAX, section)
            }
            parse_unit::UnitType::Timer => {
                let timer_unit = unit::timer_filename(&unit.name);
                let timer_active = systemctl::show_property(&timer_unit, "ActiveState")
                    .unwrap_or_else(|_| "unknown".to_string());
                let next_run_raw =
                    systemctl::show_property(&timer_unit, "NextElapseUSecRealtime")
                        .unwrap_or_else(|_| "?".to_string());
                let next_run = format_next_run(&next_run_raw);
                let schedule = unit.cron_expr.as_deref().unwrap_or("?").to_string();
                let epoch = parse_datetime_sort_key(&next_run_raw);
                let section = if timer_active != "active" {
                    Section::Disabled
                } else {
                    Section::Timer
                };
                ("timer", schedule, next_run, epoch, section)
            }
        };

        // description がコマンドと同じなら表示しない
        let description = if unit.description != unit.command {
            Some(unit.description.clone())
        } else {
            None
        };

        entries.push(Entry {
            name: unit.name.clone(),
            type_str,
            schedule,
            command: unit.command.clone(),
            status,
            description,
            legacy: unit.template_version < unit::TEMPLATE_VERSION,
            sort_key,
            section,
        });
    }

    // Sort: section first (Timer -> Service -> Disabled), then within section
    match sort {
        SortOrder::Time => {
            entries.sort_by(|a, b| {
                a.section
                    .cmp(&b.section)
                    .then(a.sort_key.cmp(&b.sort_key))
                    .then(a.name.cmp(&b.name))
            });
        }
        SortOrder::Name => {
            entries.sort_by(|a, b| {
                a.section.cmp(&b.section).then(a.name.cmp(&b.name))
            });
        }
    }

    if json {
        print_json(&entries);
    } else {
        print_table(&entries);
    }

    Ok(())
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_string();
    }
    let mut end = max - 1;
    while !s.is_char_boundary(end) && end > 0 {
        end -= 1;
    }
    format!("{}…", &s[..end])
}

fn format_status(status: &str, use_color: bool) -> String {
    let (marker, color_code) = match status {
        "active" => ("●", "\x1b[32m"),    // green
        "failed" => ("●", "\x1b[31m"),    // red
        "inactive" => ("○", "\x1b[33m"),  // yellow
        "disabled" => ("○", "\x1b[90m"),  // gray
        _ => ("○", "\x1b[90m"),           // gray
    };

    if use_color {
        format!("{color_code}{marker}\x1b[0m {status}")
    } else {
        format!("{marker} {status}")
    }
}

fn print_section_header(label: &str, _width: usize, use_color: bool) {
    let dashes = "─".repeat(3);
    if use_color {
        println!("\x1b[90m{dashes} {label} {dashes}\x1b[0m");
    } else {
        println!("{dashes} {label} {dashes}");
    }
}

fn print_table(entries: &[Entry]) {
    let use_color = std::io::stdout().is_terminal();

    // Include " [legacy]" suffix in width calculation so columns align when legacy units exist.
    let name_width = entries
        .iter()
        .map(|e| {
            if e.legacy {
                e.name.len() + " [legacy]".len()
            } else {
                e.name.len()
            }
        })
        .max()
        .unwrap_or(4)
        .max(4);
    let type_width = 7; // "service" is the longest
    let sched_width = entries
        .iter()
        .map(|e| e.schedule.len())
        .max()
        .unwrap_or(8)
        .max(8);
    let cmd_max = 40;
    let cmd_width = entries
        .iter()
        .map(|e| e.command.len().min(cmd_max))
        .max()
        .unwrap_or(7)
        .max(7);

    println!(
        "{:<name_w$}  {:<type_w$}  {:<sched_w$}  {:<cmd_w$}  STATUS",
        "NAME",
        "TYPE",
        "SCHEDULE",
        "COMMAND",
        name_w = name_width,
        type_w = type_width,
        sched_w = sched_width,
        cmd_w = cmd_width,
    );

    let total_width = name_width + type_width + sched_width + cmd_width + 8 + 10; // columns + gaps + STATUS
    let mut current_section: Option<Section> = None;

    for entry in entries {
        // Section separator
        if current_section != Some(entry.section) {
            if current_section.is_some() {
                println!();
            }
            match entry.section {
                Section::Timer => {} // no header for first section
                Section::Service => {
                    print_section_header("Services", total_width, use_color);
                }
                Section::Disabled => {
                    print_section_header("Disabled", total_width, use_color);
                }
            }
            current_section = Some(entry.section);
        }

        let cmd = truncate(&entry.command, cmd_max);
        let status = if entry.section == Section::Disabled {
            format_status("disabled", use_color)
        } else {
            format_status(&entry.status, use_color)
        };
        // Append [legacy] suffix to name so the user sees which units need upgrading.
        // Color it yellow (same palette as inactive) to make it visible but not alarming.
        let name_display = if entry.legacy {
            if use_color {
                format!("{} \x1b[33m[legacy]\x1b[0m", entry.name)
            } else {
                format!("{} [legacy]", entry.name)
            }
        } else {
            entry.name.clone()
        };
        // Compute padding manually since colored text breaks {:<width$} alignment.
        let name_raw_len = if entry.legacy {
            entry.name.len() + " [legacy]".len()
        } else {
            entry.name.len()
        };
        let name_padding = name_width.saturating_sub(name_raw_len);
        println!(
            "{}{}  {:<type_w$}  {:<sched_w$}  {:<cmd_w$}  {}",
            name_display,
            " ".repeat(name_padding),
            entry.type_str,
            entry.schedule,
            cmd,
            status,
            type_w = type_width,
            sched_w = sched_width,
            cmd_w = cmd_width,
        );

        if let Some(desc) = &entry.description {
            if use_color {
                println!("  \x1b[90m{desc}\x1b[0m");
            } else {
                println!("  {desc}");
            }
        }
    }

    // Summary footer when there are legacy units
    let legacy_count = entries.iter().filter(|e| e.legacy).count();
    if legacy_count > 0 {
        println!();
        let msg = format!(
            "{} legacy unit(s) detected. Run `sdtab upgrade` to inject new template directives without restarting.",
            legacy_count
        );
        if use_color {
            println!("\x1b[33m{}\x1b[0m", msg);
        } else {
            println!("{}", msg);
        }
    }
}

fn print_json(entries: &[Entry]) {
    let json = serde_json::to_string_pretty(entries).expect("Failed to serialize JSON");
    println!("{}", json);
}

fn format_next_run(raw: &str) -> String {
    if raw.is_empty() || raw == "n/a" {
        return "-".to_string();
    }
    raw.to_string()
}

/// Parse systemd's NextElapseUSecRealtime datetime string into a sortable u64.
/// Input format: "Wed 2026-03-04 02:00:00 JST" -> 20260304020000
fn parse_datetime_sort_key(raw: &str) -> u64 {
    // Try to extract "YYYY-MM-DD HH:MM:SS" from the string
    let parts: Vec<&str> = raw.split_whitespace().collect();
    if parts.len() >= 3 {
        // parts[1] = "2026-03-04", parts[2] = "02:00:00"
        let date_nums: String = parts[1].replace('-', "");
        let time_nums: String = parts[2].replace(':', "");
        if let Ok(val) = format!("{}{}", date_nums, time_nums).parse::<u64>() {
            return val;
        }
    }
    u64::MAX // unknown = sort last
}
