mod add;
mod apply;
mod config;
mod cron;
mod disable;
mod edit;
mod enable;
mod export;
mod init;
mod list;
mod logs;
mod parse_unit;
mod remove;
mod restart;
mod sdtabfile;
mod status;
mod systemctl;
mod unit;
mod upgrade;

use anyhow::Result;
use clap::{Parser, Subcommand, ValueEnum};

#[derive(Parser)]
#[command(name = "sdtab", about = "systemd timer management made simple")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Clone, ValueEnum)]
pub enum SortOrder {
    Time,
    Name,
}

#[derive(Subcommand)]
#[allow(clippy::large_enum_variant)]
enum Commands {
    /// Initialize sdtab (enable linger, create directories)
    Init {
        /// Slack webhook URL for failure notifications
        #[arg(long)]
        slack_webhook: Option<String>,
        /// Slack user/group ID to mention in notifications (e.g., U0700J8MN3W)
        #[arg(long)]
        slack_mention: Option<String>,
    },
    /// Add a new timer or service
    ///
    /// sdtab add "<schedule>" "<command>"
    /// Use @service for persistent daemons: sdtab add "@service" "<command>"
    Add(add::AddOptions),
    /// List all managed timers and services
    List {
        /// Output as JSON
        #[arg(long)]
        json: bool,
        /// Sort order: time (default, next run) or name
        #[arg(long, value_enum, default_value_t = SortOrder::Time)]
        sort: SortOrder,
    },
    /// Remove a timer or service
    Remove {
        /// Timer/service name to remove
        name: String,
    },
    /// Edit unit files with $EDITOR
    Edit {
        /// Timer/service name to edit
        name: String,
    },
    /// Show logs for a timer or service
    Logs {
        /// Timer/service name
        name: String,
        /// Follow log output (tail -f)
        #[arg(short, long)]
        follow: bool,
        /// Number of log lines to show
        #[arg(short = 'n', long, default_value = "50")]
        lines: u32,
        /// Filter by priority (emerg/alert/crit/err/warning/notice/info/debug)
        #[arg(short, long)]
        priority: Option<String>,
    },
    /// Restart one or more services
    ///
    /// Supports multiple names and glob patterns (e.g. `hikken-*`).
    /// Timers cannot be restarted; only daemon services are eligible.
    Restart {
        /// Service names or glob patterns. Omit when using --all.
        #[arg(required_unless_present = "all")]
        names: Vec<String>,
        /// Restart all sdtab-managed services (timers excluded)
        #[arg(long)]
        all: bool,
    },
    /// Show detailed status of a timer or service
    Status {
        /// Timer/service name
        name: String,
    },
    /// Enable (start) a timer or service
    Enable {
        /// Timer/service name to enable
        name: String,
    },
    /// Disable (stop) a timer or service without removing
    Disable {
        /// Timer/service name to disable
        name: String,
    },
    /// Export current configuration to TOML
    Export {
        /// Output file path (stdout if omitted)
        #[arg(short, long)]
        output: Option<String>,
    },
    /// Apply configuration from a TOML file
    Apply {
        /// Path to Sdtabfile.toml
        file: String,
        /// Remove units not in the file
        #[arg(long)]
        prune: bool,
        /// Show changes without applying
        #[arg(long)]
        dry_run: bool,
    },
    /// Upgrade legacy units to the current template version via drop-in overrides.
    ///
    /// Legacy units (generated by an older sdtab) still work but miss newer
    /// template directives. `sdtab upgrade` injects the missing directives as
    /// systemd drop-ins and bumps the `# sdtab:template_version=N` comment,
    /// without restarting the units.
    Upgrade {
        /// Upgrade a specific unit only (default: upgrade all legacy units)
        name: Option<String>,
        /// Show what would be upgraded without making any changes
        #[arg(long)]
        dry_run: bool,
    },
}

fn main() {
    if let Err(e) = run() {
        eprintln!("Error: {}", e);
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Init { slack_webhook, slack_mention } => init::run(slack_webhook.as_deref(), slack_mention.as_deref())?,
        Commands::Add(opts) => add::run(opts)?,
        Commands::List { json, sort } => list::run(json, sort)?,
        Commands::Remove { name } => remove::run(&name)?,
        Commands::Edit { name } => edit::run(&name)?,
        Commands::Logs { name, follow, lines, priority } => logs::run(&name, follow, lines, priority)?,
        Commands::Restart { names, all } => restart::run(&names, all)?,
        Commands::Status { name } => status::run(&name)?,
        Commands::Enable { name } => enable::run(&name)?,
        Commands::Disable { name } => disable::run(&name)?,
        Commands::Export { output } => export::run(output.as_deref())?,
        Commands::Apply { file, prune, dry_run } => apply::run(&file, prune, dry_run)?,
        Commands::Upgrade { name, dry_run } => upgrade::run(name.as_deref(), dry_run)?,
    }

    Ok(())
}
